Repository SonarSource/gh-action_release, pull requests merged in 2024-06, with the labels that each got.

#204 BUILD-5212 Support javadoc publication for private repositories
  .github/workflows/javadoc-publication.yaml
  .github/workflows/main.yaml
  README.md
Labels: enhancement

#205 BUILD-5212 Revert undesired change (required only for testing)
  .github/workflows/main.yaml
Labels: bug

#206 BUILD-5228: push releasability check outputs to datadog
  .github/workflows/build.yml
  .github/workflows/main.yaml
  datadog-ingest/README.md
  datadog-ingest/main.py
  datadog-ingest/main_test.py
Labels: DO NOT MERGE
